### ISSUE TITLE
Tambah bot untuk menjaga dependensi

### ISSUE THREAD

**Issue by ahmad-reza619** [KongkowITPekanbaru/landing-page#5]
Sedikit Saran dari saya, bagusnya kita pake bot untuk menjaga dependensi tetap up-to-date, Contohnya kayak greenkeeper. Botnya itu nanti bisa diinstal lewat [Github Marketplace](https://github.com/marketplace)

**Comment by ghost** [comment]
Kalau menurut saya jangan, soalnya admin @jufianto bilang setiap member boleh mengupload hasil desainnya dengan membuat folder baru menggunakan nama lengkap. Jadi tidak semua PR dari member lain menggunakan npm. Contoh PR saya yang saya upload di folder ahmad-ainul-rizki.

**Comment by jufianto** [comment]
yaps begitu, sebenarnya harapannya ada beberapa orang yang coba upload kesini, nanti kita diskusi dan tentukan gimana bagusnya.
jadi kan terasa project open sourcenya hahahahha

**Comment by ahmad-reza619** [comment]
> Kalau menurut saya jangan, soalnya admin @jufianto bilang setiap member boleh mengupload hasil desainnya dengan membuat folder baru menggunakan nama lengkap. Jadi tidak semua PR dari member lain menggunakan npm. Contoh PR saya yang saya upload di folder ahmad-ainul-rizki.

Wah sip deh kalo gitu, ini issuenya di close aja kalo gitu

**Comment by ahmad-reza619** [comment]
Tapi bukannya nanti gede banget tuh reponya? 🤔
